spring:
  application:
    name: PostgresqlDemo

  datasource:
    username: postgres
    password: user
    url: jdbc:postgresql://localhost:5432/test123

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
